### PR TITLE
Updated compile command with -F flag

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Closing because discrepancy between Dr. Reeve's machine and my machine

**Comment by brentreeves** [comment]
Maybe just add a note for the "High Sierra" types?

**Comment by cxs13b** [comment]
Will do, I'll just open up another pull request, because of additional functionality

**Comment by ghost** [comment]
Added note to README.md, and also updated Smokescreen with speed parameter. Should be good to deploy anytime.

**Pull request merged**
