### PR TITLE
Tug Of War v0.1

### PR DESCRIPTION
**Pull request by ghost**
Working Tug Of War example. Utilizes IR to play "Tug of War." Is working, but needs "aesthetic improvements"

### CODE REVIEW

**Review by brentreeves — COMMENTED** [review]
Apologies... I've been using SIM_NODES to test, but we should use NODE_COUNT.

**Comment by ghost** [comment]
Fixed merge conflicts and SIM_NODE/NODE_COUNT discrepancy. Simulator will look weird, as it only shows 13 nodes (instead of all 35). It looks all blue in the simulator. It's not, it's only just showing part of the Blue Team.

**Comment by brentreeves** [comment]
I have node_count set to 13 in constants.h and when I run it, it stops reacting after 13 clicks.  Perhaps related to the number of nodes?

**Comment by ghost** [comment]
Hmm, interesting. I'll check it out

**Comment by ghost** [comment]
In interactiveEffect.h, _movementOn method returns if _activeMovements == NODE_COUNT. This is why that bug was appearing. I decrement _activeMovement in TugOfWar's _movementOn method.

**Comment by ghost** [comment]
Game now shows winner, blinks winning color, then resets

**Pull request merged**
